//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prodazha_avto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cars()
        {
            this.Sales = new HashSet<Sales>();
        }
    
        public int id_car { get; set; }
        public Nullable<int> id_typeofcuzov { get; set; }
        public int model { get; set; }
        public string color { get; set; }
        public decimal price { get; set; }
        public int quantity { get; set; }
        public Nullable<int> image { get; set; }
    
        public virtual CarModel CarModel { get; set; }
        public virtual CarTypes CarTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales> Sales { get; set; }
        public virtual CarImg CarImg { get; set; }
    }
}
