//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prodazha_avto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int id { get; set; }
        public string imya { get; set; }
        public string familiya { get; set; }
        public string otchestvo { get; set; }
        public string adress { get; set; }
    }
}
