//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prodazha_avto
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class user270_dbEntities : DbContext
    {
        public user270_dbEntities()
            : base("name=user270_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CarBrand> CarBrand { get; set; }
        public virtual DbSet<CarModel> CarModel { get; set; }
        public virtual DbSet<CarRole> CarRole { get; set; }
        public virtual DbSet<Cars> Cars { get; set; }
        public virtual DbSet<CarTypes> CarTypes { get; set; }
        public virtual DbSet<CarUser> CarUser { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Sales> Sales { get; set; }
        public virtual DbSet<CarImg> CarImg { get; set; }
    }
}
