//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prodazha_avto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int id_sale { get; set; }
        public Nullable<int> id_car { get; set; }
        public Nullable<int> id_user { get; set; }
        public System.DateTime sale_date { get; set; }
        public decimal sale_price { get; set; }
        public string reviews { get; set; }
    
        public virtual Cars Cars { get; set; }
        public virtual CarUser CarUser { get; set; }
    }
}
